# Generated by Django 4.0 on 2022-01-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monsters", "0002_alter_monster_options_alter_specialattack_options_and_more"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="liked_monsters",
            field=models.ManyToManyField(to="monsters.Monster"),
        ),
    ]
