# Generated by Django 4.0 on 2021-12-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
