# Generated by Django 4.0 on 2021-12-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0003_alter_monster_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='image',
            field=models.ImageField(blank=True, upload_to='monsters'),
        ),
    ]
